# -*- mode: ruby -*-
# vi: set ft=ruby :
# encoding: utf-8

Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |v|
    v.gui = false
  end

  config.vm.define :log do |log|
    log.vm.box = "ubuntu/trusty64"
    log.vm.hostname = 'log.localhost.localdomain'

    log.vm.network :private_network, ip: "192.168.254.10"

    log.vm.provision "puppet" do |puppet|
      puppet.module_path = "modules"
      puppet.hiera_config_path = "hiera/hiera.yaml"
      puppet.facter = {
        "environment" => "vagrant"
      }
      puppet.working_directory = "/vagrant"
    end

    log.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 1572]
    end
  end

  config.vm.define :web do |web|
    web.vm.box = "ubuntu/trusty64"
    web.vm.hostname = 'web.localhost.localdomain'

    web.vm.network :private_network, ip: "192.168.254.11"

    web.vm.provision "puppet" do |puppet|
      puppet.module_path = "modules"
      puppet.hiera_config_path = "hiera/hiera.yaml"
      puppet.facter = {
        "environment" => "vagrant"
      }
      puppet.working_directory = "/vagrant"
    end

    web.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
    end
  end

  config.vm.define :customer do |customer|
    customer.vm.box = "ubuntu/trusty64"
    customer.vm.hostname = 'customer.localhost.localdomain'

    customer.vm.network :private_network, ip: "192.168.254.12"

    customer.vm.provision "puppet" do |puppet|
      puppet.module_path = "modules"
      puppet.hiera_config_path = "hiera/hiera.yaml"
      puppet.facter = {
        "environment" => "vagrant"
      }
      puppet.working_directory = "/vagrant"
    end

    customer.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
    end
  end

  config.vm.define :product do |product|
    product.vm.box = "ubuntu/trusty64"
    product.vm.hostname = 'product.localhost.localdomain'

    product.vm.network :private_network, ip: "192.168.254.13"

    product.vm.provision "puppet" do |puppet|
      puppet.module_path = "modules"
      puppet.hiera_config_path = "hiera/hiera.yaml"
      puppet.facter = {
        "environment" => "vagrant"
      }
      puppet.working_directory = "/vagrant"
    end

    product.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
    end
  end

  config.vm.define :cart do |cart|
    cart.vm.box = "ubuntu/trusty64"
    cart.vm.hostname = 'cart.localhost.localdomain'

    cart.vm.network :private_network, ip: "192.168.254.14"

    cart.vm.provision "puppet" do |puppet|
      puppet.module_path = "modules"
      puppet.hiera_config_path = "hiera/hiera.yaml"
      puppet.facter = {
        "environment" => "vagrant"
      }
      puppet.working_directory = "/vagrant"
    end

    cart.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
    end
  end

  config.vm.define :zipkin do |zipkin|
    zipkin.vm.box = "ubuntu/trusty64"
    zipkin.vm.hostname = 'zipkin.localhost.localdomain'

    zipkin.vm.network :private_network, ip: "192.168.254.20"

    zipkin.vm.provision "puppet" do |puppet|
      puppet.module_path = "modules"
      puppet.hiera_config_path = "hiera/hiera.yaml"
      puppet.facter = {
        "environment" => "vagrant"
      }
      puppet.working_directory = "/vagrant"
    end

    zipkin.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 1572]
    end
  end
end
